### PR TITLE
Flatten out _ chars when comparing to url

### LINKED ISSUE #12: Failing on certain usernames
👋 Thanks for creating this! I'm getting some pretty weird results that just aren't adding up. I've checked the regex used in this library against a link like `https://twitter.com/Ana_M_Medina/status/1045730232743813121` (which it does correctly match), but when the library is actually performing the swaps, I noticed the debug and eventual widget output doesn't include it. It looks like it may have something to do with the multiple underscores in the username, but the regex seemed to correctly handle it, so I'm a bit 🤷‍♂️ on what's up here. Any thoughts would be greatly appreciated. Thanks!

cc @isaacs

### PR DESCRIPTION
**Pull request by isaacs**
Fix #12

### CODE REVIEW

**Comment by zslabs** [comment]
👋 Wanted to chime-in and say testing this branch worked perfectly! Looking forward to this getting merged/released; really appreciate you looking into this!

**Comment by jmolivas** [comment]
Thanks for the PR @isaacs. Will tag a new release tomorrow Tuesday or Wednesday.

**Comment by zslabs** [comment]
@jmolivas Would it be possible to get a release tagged with this one? Thanks!

**Comment by jmolivas** [comment]
@jmolivas @isaacs new release 0.2.1 was tagged thanks for the sending and testing the PR.

**Comment by zslabs** [comment]
@jmolivas I think something may have happened with the release; when installing `"@weknow/gatsby-remark-twitter": "^0.2.1"` and looking at the `node_modules` source, the fix from this PR is not in there. When installing directly from GitHub with `"@weknow/gatsby-remark-twitter": "weknowinc/gatsby-remark-twitter#0.2.1"` I can see the updated changes.

**Comment by jmolivas** [comment]
@zslabs  Reviewing and tagging again, thanks for reporting.

**Comment by zslabs** [comment]
I'm still having to use the `"@weknow/gatsby-remark-twitter": "weknowinc/gatsby-remark-twitter#0.2.1"` to include the changes from this. Are you seeing the same on your end?

**Comment by isaacs** [comment]
@zslabs Yes, what you are observing is accurate. https://github.com/weknowinc/gatsby-remark-twitter/issues/17

**Comment by jmolivas** [comment]
Fixed on `0.2.3` following steps provided by @isaacs, can you re-try @zslabs

**Comment by zslabs** [comment]
Works great, thanks for the quick response on this one!

**Pull request merged**
